In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report

In [5]:
df = pd.read_csv("seeds_dataset.csv")

In [7]:
df.head()

Area  Perimeter   Compactness  Length of kernel  Width of kernel  \
0  15.26      14.84        0.8710             5.763            3.312   
1  14.88      14.57        0.8811             5.554            3.333   
2  14.29      14.09        0.9050             5.291            3.337   
3  13.84      13.94        0.8955             5.324            3.379   
4  16.14      14.99        0.9034             5.658            3.562   

   Asymmetry coefficient  Length of kernel groove  Class  
0                  2.221                    5.220      1  
1                  1.018                    4.956      1  
2                  2.699                    4.825      1  
3                  2.259                    4.805      1  
4                  1.355                    5.175      1

In [9]:
df_x = df.drop(labels=["Class"] , axis=1)
df_y = df["Class"]

In [11]:
scaler = StandardScaler()
x_nrm = scaler.fit_transform(df_x)
y = df_y.values

In [13]:
x_train,x_val,y_train,y_val = train_test_split(x_nrm , y , train_size=0.8)

In [15]:
model = DecisionTreeClassifier()
# model = DecisionTreeRegressor()

In [17]:
results = model.fit(x_train , y_train)

In [19]:
y_hat_train = model.predict(x_train)
y_hat_test = model.predict(x_val)

In [30]:
metrics.accuracy_score(y_val, y_hat_test)

0.9047619047619048

In [23]:
print("Confusion Matrix:\n", confusion_matrix(y_val, y_hat_test))
print("\nClassification Report:\n", classification_report(y_val, y_hat_test))

Confusion Matrix:
 [[10  0  1]
 [ 2 14  0]
 [ 4  0 11]]

Classification Report:
               precision    recall  f1-score   support

           1       0.62      0.91      0.74        11
           2       1.00      0.88      0.93        16
           3       0.92      0.73      0.81        15

    accuracy                           0.83        42
   macro avg       0.85      0.84      0.83        42
weighted avg       0.87      0.83      0.84        42

